import { useEffect, useRef, useState } from 'react'
import { api, legacyUrl } from '../../../api/client'
const Icon=({children})=><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">{children}</svg>
export default function NotificationTopbar({user,unread,channel}){
 const [open,setOpen]=useState(false),[dark,setDark]=useState(()=>(document.cookie.match(/(?:^|; )rms_theme=(dark|light)(?:;|$)/)?.[1]||localStorage.getItem('theme'))==='dark');const wrap=useRef(null)
 useEffect(()=>{const close=e=>{if(wrap.current&&!wrap.current.contains(e.target))setOpen(false)},escape=e=>{if(e.key==='Escape')setOpen(false)};addEventListener('click',close);addEventListener('keydown',escape);return()=>{removeEventListener('click',close);removeEventListener('keydown',escape)}},[])
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('theme',dark?'dark':'light');document.cookie=`rms_theme=${dark?'dark':'light'}; Path=/; Max-Age=31536000; SameSite=Lax`},[dark])
 async function logout(){await api('/api/auth/logout',{method:'POST'});localStorage.clear();sessionStorage.clear();location.replace(legacyUrl('/'))}
 const name=user?.name||user?.username||'Admin'
 return <header className="vanilla-topbar"><div className="vanilla-topbar-left"><a className="vanilla-icon-button quick-button" href="/app/lobby" title="Open navigation"><Icon><path d="M11 19l-7-7 7-7m8 14l-7-7 7-7"/></Icon></a><div className="vanilla-brand"><span><Icon><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.3 2.3c-.6.6-.2 1.7.7 1.7H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/></Icon></span><div><strong>{user?.shop_name||'POS System'}</strong><small>{user?.role==='superadmin'?'Master Control':'Management'}</small></div></div></div><div className="vanilla-user-controls"><div className="vanilla-user-copy"><strong>{name}</strong><small>{user?.role}</small></div><a className="vanilla-icon-button bell-button" href={channel==='inbox'?'/app/notification-inbox':'/app/notifications'} title="Notifications"><Icon><path d="M15 17h5l-1.4-1.4A2 2 0 0118 14.2V11a6 6 0 10-12 0v3.2c0 .5-.2 1-.6 1.4L4 17h5m6 0a3 3 0 01-6 0m6 0H9"/></Icon>{unread>0&&<b>{unread>99?'99+':unread}</b>}</a><a className="vanilla-icon-button" href="/app/lobby" title="Switch Module"><Icon><path d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zm10 0a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zm10 0a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"/></Icon></a><div className="vanilla-profile" ref={wrap}><button className="vanilla-profile-trigger" onClick={e=>{e.stopPropagation();setOpen(v=>!v)}} aria-label="Open profile menu" aria-expanded={open}><span>{name.charAt(0).toUpperCase()}</span><Icon><path d="M19 9l-7 7-7-7"/></Icon></button><div className={`vanilla-profile-menu ${open?'active':''}`}><div className="vanilla-mobile-user"><strong>{name}</strong><small>{user?.role}</small></div><button onClick={()=>{setDark(v=>!v);setOpen(false)}}>Switch theme</button><a href="/app/lobby">Switch module</a><button className="sign-out" onClick={logout}>Sign out</button></div></div></div></header>
}
