const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const read = relative => fs.readFileSync(path.join(__dirname, '..', relative), 'utf8')

test('Sales is routed to React while the vanilla fallback remains available', () => {
  const app = read('frontend/src/App.jsx')
  const lobby = read('services/LobbyService.js')
  const reactSales = read('frontend/src/modules/sales/SalesPage.jsx')
  const reactPayment = read('frontend/src/modules/pos/PosPaymentModal.jsx')
  const dashboardMetrics = read('frontend/src/modules/dashboard/components/DashboardMetrics.jsx')
  const registerPayments = read('public/js/register-payments.js')
  const vanilla = read('public/js/app.js')

  assert.ok(app.includes('/app/sales'))
  assert.ok(app.includes('<SalesPage />'))
  assert.ok(lobby.includes('sales-history'))
  assert.ok(lobby.includes('/app/sales'))
  for (const marker of ['sales_panel', 'payment_status', 'sales.take_payment', 'sales.return', '/api/print-jobs/queue', 'autoprint', 'refund_price', 'payment_method: method', 'is_damage', 'returned_qty', 'return-complete', '/api/sales/returns/', 'Print Return Receipt']) {
    assert.ok(reactSales.includes(marker), marker)
  }
  assert.ok(vanilla.includes('async function renderSalesHistory'))
  assert.ok(vanilla.includes('tip_payment_method'))
  assert.ok(vanilla.includes('Tip Method'))
  assert.ok(reactPayment.includes('tip_payment_method'))
  assert.ok(reactPayment.includes('Bill Payment Method'))
  assert.ok(reactSales.includes('sale.tip_payment_method'))
  assert.ok(registerPayments.includes('row.tip_payment_method'))
  assert.ok(dashboardMetrics.includes('tips.cash_tips'))
  assert.ok(dashboardMetrics.includes('tips.card_tips'))
  assert.ok(dashboardMetrics.includes('tips.online_tips'))
})
