const express = require('express');
const { requirePermission } = require('../../../authorization/middleware');
const controller = require('./attendance.controller');
const router = express.Router();
router.get('/templates', requirePermission('attendance.view'), controller.templates);
router.get('/staff-options', requirePermission('attendance.view'), controller.staffOptions);
router.post('/templates', requirePermission('attendance.manage_schedules'), controller.createTemplate);
router.put('/templates/:id', requirePermission('attendance.manage_schedules'), controller.versionTemplate);
router.put('/schedules/weekly', requirePermission('attendance.manage_schedules'), controller.schedule);
router.post('/holidays', requirePermission('attendance.manage_schedules'), controller.holiday);
router.get('/clock/state', requirePermission('attendance.view', 'attendance.clock'), controller.clockState);
router.post('/clock', requirePermission('attendance.clock'), controller.clock);
router.get('/calendar', requirePermission('attendance.view'), controller.calendar);
router.get('/corrections', requirePermission('attendance.approve'), controller.corrections);
router.post('/corrections', requirePermission('attendance.correct'), controller.requestCorrection);
router.patch('/corrections/:id/review', requirePermission('attendance.approve'), controller.reviewCorrection);
router.get('/snapshots', requirePermission('attendance.approve'), controller.snapshots);
router.post('/snapshots', requirePermission('attendance.approve'), controller.createSnapshot);
router.patch('/snapshots/:id/approve', requirePermission('attendance.approve'), controller.approveSnapshot);
router.get('/daily-register', requirePermission('attendance.view'), controller.dailyRegister);
router.post('/daily-register', requirePermission('attendance.mark_daily'), controller.markDailyRegister);
router.get('/shift-register', requirePermission('attendance.view'), controller.shiftRegister);
router.post('/shift-register', requirePermission('attendance.mark_daily'), controller.submitShiftRegister);
module.exports = router;
