import { useEffect, useState } from 'react'
import { api, legacyUrl } from '../../api/client'
import { formatShopCurrency } from '../../currency'

const money = value => formatShopCurrency(Number(value || 0))
const label = row => row.method || row.channel || row.name || row.product_name || row.username || 'Unknown'
const amount = row => row.amount ?? row.total ?? row.sales ?? row.revenue ?? row.received_sales ?? 0
function Table({ title, rows = [] }) { return <section className='rounded-2xl border bg-white p-5'><h2 className='text-lg font-bold mb-3'>{title}</h2><table className='w-full text-sm'><tbody>{rows.map((row, i) => <tr className='border-t' key={i}><td className='py-3'>{label(row)}</td><td className='py-3 text-right'>{money(amount(row))}</td></tr>)}</tbody></table>{!rows.length && <p className='text-slate-500'>No records.</p>}</section> }
export default function ReportsPage() {
  const [user, setUser] = useState(null), [period, setPeriod] = useState('7days'), [from, setFrom] = useState(''), [to, setTo] = useState(''), [data, setData] = useState(null), [error, setError] = useState('')
  useEffect(() => { document.title = 'Reports — DevForge RMS'; api('/api/auth/me').then(({ user }) => { if (user.role !== 'superadmin' && !user.permissions?.includes('reports.view')) throw new Error('You do not have permission to view Reports.'); setUser(user) }).catch(e => e.status === 401 ? window.location.replace(legacyUrl('/')) : setError(e.message)) }, [])
  useEffect(() => { if (!user) return; const q = new URLSearchParams({ period }); if (period === 'custom') { q.set('from', from); q.set('to', to) } api('/api/reports/summary?' + q).then(setData).catch(e => setError(e.message)) }, [user, period, from, to])
  const metrics = [['Net sales', data?.kpi?.totalSales], ['Orders', data?.kpi?.totalOrders, true], ['Tax', data?.summary?.totalTax], ['Tips', data?.totalTipsCollected], ['Refunds', data?.summary?.totalRefunds], ['Net profit', data?.netProfit]]
  function csv() { const rows = [['Metric','Value'], ...metrics.map(x => [x[0], Number(x[1] || 0)])]; const blob = new Blob([rows.map(r => r.join(',')).join('\n')], { type:'text/csv' }); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='reports.csv'; a.click(); URL.revokeObjectURL(a.href) }
  return <main className='min-h-screen bg-slate-50 p-4 sm:p-8 text-slate-900'><header className='max-w-7xl mx-auto flex flex-wrap justify-between gap-4'><div><button onClick={() => location.assign('/app/lobby')} className='border rounded-xl px-3 py-2 bg-white'>← Modules</button><h1 className='text-3xl font-black mt-3'>Reports</h1><p className='text-slate-500'>{user?.shop_name}</p></div><div className='flex gap-2 items-center'><button onClick={() => print()} className='border rounded-xl px-4 py-2 bg-white'>Print</button><button onClick={csv} disabled={!data} className='rounded-xl px-4 py-2 bg-teal-700 text-white'>Export CSV</button></div></header><section className='max-w-7xl mx-auto my-6 flex flex-wrap gap-3 bg-white border rounded-2xl p-4'><select value={period} onChange={e => {setData(null);setPeriod(e.target.value)}} className='border rounded-lg p-2'><option value='today'>Today</option><option value='7days'>Last 7 days</option><option value='30days'>Last 30 days</option><option value='custom'>Custom</option></select>{period === 'custom' && <><input type='date' value={from} onChange={e => setFrom(e.target.value)} className='border rounded-lg p-2'/><input type='date' min={from} value={to} onChange={e => setTo(e.target.value)} className='border rounded-lg p-2'/></>}</section>{error ? <p className='max-w-7xl mx-auto text-red-600'>{error}</p> : !data ? <p className='max-w-7xl mx-auto'>Preparing report…</p> : <><section className='max-w-7xl mx-auto grid sm:grid-cols-3 gap-3'>{metrics.map(([name,value,plain]) => <article key={name} className='rounded-2xl border bg-white p-5'><span className='text-slate-500'>{name}</span><strong className='block text-2xl mt-1'>{plain ? Number(value || 0).toLocaleString() : money(value)}</strong></article>)}</section><div className='max-w-7xl mx-auto grid lg:grid-cols-2 gap-3 mt-3'><Table title='Payment methods' rows={data.paymentBreakdown}/><Table title='Sales channels' rows={data.channelBreakdown}/><Table title='Top products' rows={data.topProducts}/><Table title='Staff collections' rows={data.staffPerformance}/></div><footer className='max-w-7xl mx-auto mt-5 text-slate-500'>Data as of {new Date(data.dataAsOf).toLocaleString()} · {data.metricVersion}</footer></>}</main>
}
