import { useCallback, useEffect, useState } from 'react'
import { api } from '../../../api/client'

export default function AttendanceCorrectionsPanel({ staff, canApprove }) {
  const [requests, setRequests] = useState([]); const [form, setForm] = useState({ staff_profile_id: '', business_date: new Date().toISOString().slice(0, 10), correction_type: 'add_event', proposed_event_type: 'clock_in', proposed_occurred_at: '', proposed_absence_type: 'authorized', reason: '' }); const [error, setError] = useState('')
  const load = useCallback(async () => { if (canApprove) try { setRequests(await api('/api/attendance/corrections')) } catch (requestError) { setError(requestError.message) } }, [canApprove])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  async function submit(event) { event.preventDefault(); setError(''); const body = { ...form, proposed_occurred_at: form.proposed_occurred_at ? new Date(form.proposed_occurred_at).toISOString() : undefined }; if (form.correction_type === 'classify_absence') { delete body.proposed_event_type; delete body.proposed_occurred_at } else delete body.proposed_absence_type; try { await api('/api/attendance/corrections', { method: 'POST', body }); set('reason', ''); await load() } catch (requestError) { setError(requestError.message) } }
  async function review(id, decision) { const note = window.prompt(`${decision === 'approved' ? 'Approval' : 'Rejection'} note:`); if (!note) return; try { await api(`/api/attendance/corrections/${id}/review`, { method: 'PATCH', body: { decision, note } }); await load() } catch (requestError) { setError(requestError.message) } }
  return <section className="attendance-corrections"><header><h3>Attendance corrections</h3><p>Raw events stay immutable. Approved requests create separate adjustment records.</p></header>{error && <div className="form-error">{error}</div>}<form className="staff-form" onSubmit={submit}><div className="form-grid"><label>Staff<select value={form.staff_profile_id} onChange={(e) => set('staff_profile_id', e.target.value)} required><option value="">Select staff</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label>Business date<input type="date" value={form.business_date} onChange={(e) => set('business_date', e.target.value)} required /></label></div><label>Correction type<select value={form.correction_type} onChange={(e) => set('correction_type', e.target.value)}><option value="add_event">Add missing event</option><option value="classify_absence">Classify absence</option></select></label>{form.correction_type === 'classify_absence' ? <label>Absence type<select value={form.proposed_absence_type} onChange={(e) => set('proposed_absence_type', e.target.value)}><option value="authorized">Authorized</option><option value="unauthorized">Unauthorized</option><option value="sick">Sick</option><option value="other">Other</option></select></label> : <div className="form-grid"><label>Event<select value={form.proposed_event_type} onChange={(e) => set('proposed_event_type', e.target.value)}><option value="clock_in">Clock in</option><option value="break_start">Break start</option><option value="break_end">Break end</option><option value="clock_out">Clock out</option></select></label><label>Proposed time<input type="datetime-local" value={form.proposed_occurred_at} onChange={(e) => set('proposed_occurred_at', e.target.value)} required /></label></div>}<label>Reason<textarea value={form.reason} onChange={(e) => set('reason', e.target.value)} required minLength="3" /></label><button className="primary-button">Submit for approval</button></form>{canApprove && <div className="correction-list"><h4>Review queue</h4>{requests.filter((item) => item.status === 'pending').map((item) => <article key={item.id}><div><strong>{item.full_name}</strong><span>{item.business_date} · {item.correction_type.replaceAll('_', ' ')}</span><p>{item.reason}</p></div><div><button className="secondary-button" onClick={() => review(item.id, 'rejected')}>Reject</button><button className="primary-button" onClick={() => review(item.id, 'approved')}>Approve</button></div></article>)}</div>}</section>
}
