import { useEffect, useState } from 'react'
import { api } from '../../../api/client'

const today = new Date(); const first = new Date(today.getFullYear(), today.getMonth(), 1).toISOString().slice(0, 10); const last = new Date(today.getFullYear(), today.getMonth() + 1, 0).toISOString().slice(0, 10)
const STATUS = { present: 'Present', late: 'Late', early_departure: 'Early departure', missing_clock_in: 'Missing clock-in', missing_clock_out: 'Missing clock-out', scheduled: 'Scheduled', weekly_off: 'Weekly off', holiday: 'Holiday', approved_leave: 'Approved leave', unauthorized_absence: 'Unauthorized absence', authorized_absence: 'Authorized absence', sick_absence: 'Sick absence', other_absence: 'Other absence' }
export default function AttendanceCalendar({ staff, canManage }) {
  const [range, setRange] = useState({ from: first, to: last, staff_profile_id: '' }); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { const timer = window.setTimeout(() => { const params = new URLSearchParams(Object.fromEntries(Object.entries(range).filter(([, value]) => value))); api(`/api/attendance/calendar?${params}`).then(setData).catch((requestError) => setError(requestError.message)) }, 180); return () => window.clearTimeout(timer) }, [range])
  const set = (field, value) => setRange((current) => ({ ...current, [field]: value }))
  return <section className="attendance-calendar"><header><div><h3>Attendance calendar</h3><p>{data?.timezone ? `Business dates use ${data.timezone}.` : 'Loading attendance…'}</p></div></header><div className="attendance-filters"><label>From<input type="date" value={range.from} onChange={(e) => set('from', e.target.value)} /></label><label>To<input type="date" value={range.to} onChange={(e) => set('to', e.target.value)} /></label>{canManage && <label>Staff<select value={range.staff_profile_id} onChange={(e) => set('staff_profile_id', e.target.value)}><option value="">All staff</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label>}</div>{error && <div className="form-error">{error}</div>}{data && <><div className="attendance-summary"><span><strong>{data.summary.present || 0}</strong> Present</span><span><strong>{data.summary.late || 0}</strong> Late</span><span><strong>{(data.summary.missing_clock_in || 0) + (data.summary.missing_clock_out || 0)}</strong> Missing clocks</span><span><strong>{Math.round((data.summary.work_minutes || 0) / 60)}h</strong> Worked</span></div><div className="attendance-table-shell"><table className="attendance-table"><thead><tr><th>Date</th><th>Staff</th><th>Shift</th><th>Status</th><th>Worked</th><th>Exceptions</th></tr></thead><tbody>{data.rows.map((row) => <tr key={`${row.staff.id}-${row.date}`}><td data-label="Date">{new Date(`${row.date}T00:00:00`).toLocaleDateString()}</td><td data-label="Staff"><strong>{row.staff.full_name}</strong><span>{row.staff.employee_id}</span></td><td data-label="Shift">{row.shift_name || '—'}</td><td data-label="Status"><span className={`attendance-status ${row.status}`}>{STATUS[row.status] || row.status}</span></td><td data-label="Worked">{row.work_minutes ? `${Math.floor(row.work_minutes / 60)}h ${row.work_minutes % 60}m` : '—'}</td><td data-label="Exceptions">{row.late_minutes ? `${row.late_minutes}m late` : row.early_departure_minutes ? `${row.early_departure_minutes}m early` : '—'}</td></tr>)}</tbody></table></div></>}</section>
}
