import { useState } from 'react'
import { api } from '../../../api/client'

const EMPTY = { name: '', start_time: '09:00', end_time: '17:00', is_overnight: false, unpaid_break_minutes: 0, grace_minutes: 10 }
export default function ShiftTemplateManager({ templates, onChanged }) {
  const [form, setForm] = useState(EMPTY); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); try { await api('/api/attendance/templates', { method: 'POST', body: form }); setForm(EMPTY); await onChanged() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  return <section className="shift-template-manager"><header><h3>Shift templates</h3><p>Changes create new versions so historical schedules remain stable.</p></header>{error && <div className="form-error">{error}</div>}<div className="template-list">{templates.map((template) => <article key={template.id}><strong>{template.name}</strong><span>{String(template.start_time).slice(0, 5)}–{String(template.end_time).slice(0, 5)}{template.is_overnight ? ' · Overnight' : ''}</span><small>Break {template.unpaid_break_minutes}m · Grace {template.grace_minutes ?? 'default'}m · v{template.version}</small></article>)}</div><form className="staff-form" onSubmit={submit}><div className="form-grid"><label>Name<input value={form.name} onChange={(e) => set('name', e.target.value)} required /></label><label className="check-row"><input type="checkbox" checked={form.is_overnight} onChange={(e) => set('is_overnight', e.target.checked)} /> Overnight shift</label></div><div className="form-grid"><label>Starts<input type="time" value={form.start_time} onChange={(e) => set('start_time', e.target.value)} required /></label><label>Ends<input type="time" value={form.end_time} onChange={(e) => set('end_time', e.target.value)} required /></label></div><div className="form-grid"><label>Unpaid break minutes<input type="number" min="0" max="720" value={form.unpaid_break_minutes} onChange={(e) => set('unpaid_break_minutes', Number(e.target.value))} /></label><label>Grace minutes<input type="number" min="0" max="180" value={form.grace_minutes} onChange={(e) => set('grace_minutes', Number(e.target.value))} /></label></div><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Create template'}</button></form></section>
}
