import { useEffect, useState } from 'react'
import { api } from '../../../api/client'
import StaffModal from './StaffModal'
import StaffAssignmentHistory from './StaffAssignmentHistory'

export default function StaffAssignmentPanel({ profile, canUpdate, isSuperadmin, onClose, onChanged }) {
  const [options, setOptions] = useState(null); const [history, setHistory] = useState([]); const [form, setForm] = useState(null)
  const [shops, setShops] = useState([])
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const today = new Date().toISOString().slice(0, 10)
  useEffect(() => { Promise.all([api('/api/staff/organization/options'), api(`/api/staff/${profile.id}/assignment`), isSuperadmin ? api('/api/shops') : Promise.resolve([])]).then(([nextOptions, result, nextShops]) => {
    setOptions(nextOptions); setHistory(result.history); setShops(nextShops); setForm({ department_id: result.assignment.department_id || '', designation_id: result.assignment.designation_id || '', manager_staff_id: result.assignment.manager_staff_id || '', primary_location_id: result.assignment.primary_location_id || '', classification_id: result.assignment.classification_id || '', effective_date: today, reason: '' })
  }).catch((requestError) => setError(requestError.message)) }, [profile.id, today, isSuperadmin])
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); try { await api(`/api/staff/${profile.id}/assignment`, { method: 'PUT', body: form }); await onChanged(); onClose() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  async function transfer(event) { event.preventDefault(); if (!window.confirm('Transfer this employee to another restaurant? Existing shop roles will be removed and active sessions revoked.')) return; setSaving(true); try { await api(`/api/staff/${profile.id}/transfer`, { method: 'POST', body: { target_shop_id: event.currentTarget.target_shop_id.value, effective_date: event.currentTarget.effective_date.value, reason: event.currentTarget.reason.value } }); await onChanged(); onClose() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  return <StaffModal title={`Organization · ${profile.full_name}`} onClose={onClose} wide><div className="assignment-panel">{error && <div className="form-error">{error}</div>}{!form || !options ? <p>Loading assignment…</p> : <>
    <form className="staff-form" onSubmit={save}><div className="form-grid"><label>Department<select value={form.department_id} onChange={(e) => set('department_id', e.target.value)} disabled={!canUpdate}><option value="">Unassigned</option>{options.departments.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Designation<select value={form.designation_id} onChange={(e) => set('designation_id', e.target.value)} disabled={!canUpdate}><option value="">Unassigned</option>{options.designations.filter((x) => !x.department_id || Number(x.department_id) === Number(form.department_id)).map((x) => <option key={x.id} value={x.id}>{x.title}</option>)}</select></label></div>
      <div className="form-grid"><label>Reports to<select value={form.manager_staff_id} onChange={(e) => set('manager_staff_id', e.target.value)} disabled={!canUpdate}><option value="">No manager</option>{options.managers.filter((x) => x.id !== profile.id).map((x) => <option key={x.id} value={x.id}>{x.full_name} · {x.employee_id}</option>)}</select></label><label>Work location<select value={form.primary_location_id} onChange={(e) => set('primary_location_id', e.target.value)} disabled={!canUpdate}><option value="">Unassigned</option>{options.locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
      <label>Employment classification<select value={form.classification_id} onChange={(e) => set('classification_id', e.target.value)} disabled={!canUpdate}><option value="">Use profile employment type</option>{options.classifications.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      {canUpdate && <><div className="form-grid"><label>Effective date<input type="date" value={form.effective_date} onChange={(e) => set('effective_date', e.target.value)} required /></label><label>Reason<input value={form.reason} onChange={(e) => set('reason', e.target.value)} required maxLength="1000" /></label></div><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save assignment'}</button></>}
    </form><StaffAssignmentHistory events={history} />
    {isSuperadmin && <form className="transfer-form" onSubmit={transfer}><h3>Cross-restaurant transfer</h3><p>Platform administrators can move the profile and linked login. Target assignments must be configured afterward.</p><div className="form-grid"><label>Target restaurant<select name="target_shop_id" required><option value="">Select restaurant</option>{shops.filter((shop) => Number(shop.id) !== Number(profile.shop_id) && shop.status === 'active').map((shop) => <option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label><label>Effective date<input name="effective_date" type="date" defaultValue={today} required /></label></div><label>Transfer reason<input name="reason" required maxLength="1000" /></label><button className="danger-button" disabled={saving}>Transfer employee</button></form>}
    <footer><button className="secondary-button" onClick={onClose}>Close</button></footer></>}
  </div></StaffModal>
}
