import { useState } from 'react'
import { api } from '../../../api/client'

const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
export default function WeeklyScheduleEditor({ staff, templates }) {
  const [staffId, setStaffId] = useState(''); const [effective, setEffective] = useState(new Date().toISOString().slice(0, 10))
  const [days, setDays] = useState(() => DAYS.map((_, weekday) => ({ weekday, shift_template_id: '', is_day_off: weekday === 0 })))
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  function change(index, field, value) { setDays((current) => current.map((day, position) => position === index ? { ...day, [field]: value, ...(field === 'is_day_off' && value ? { shift_template_id: '' } : {}) } : day)) }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { await api('/api/attendance/schedules/weekly', { method: 'PUT', body: { staff_profile_id: staffId, effective_from: effective, days } }); setMessage('Weekly schedule saved with an effective date.') } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  return <section className="weekly-schedule"><header><h3>Weekly schedules</h3><p>New schedules close the previous effective period without deleting history.</p></header>{error && <div className="form-error">{error}</div>}{message && <div className="form-success">{message}</div>}<form onSubmit={submit}><div className="form-grid"><label>Staff member<select value={staffId} onChange={(e) => setStaffId(e.target.value)} required><option value="">Select staff</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name} · {person.employee_id}</option>)}</select></label><label>Effective from<input type="date" value={effective} onChange={(e) => setEffective(e.target.value)} required /></label></div><div className="schedule-days">{days.map((day, index) => <div key={day.weekday}><strong>{DAYS[day.weekday]}</strong><label className="check-row"><input type="checkbox" checked={day.is_day_off} onChange={(e) => change(index, 'is_day_off', e.target.checked)} /> Day off</label><select aria-label={`${DAYS[day.weekday]} shift`} value={day.shift_template_id} onChange={(e) => change(index, 'shift_template_id', e.target.value)} disabled={day.is_day_off} required={!day.is_day_off}><option value="">Select shift</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></div>)}</div><button className="primary-button" disabled={saving || !templates.length}>{saving ? 'Saving…' : 'Save weekly schedule'}</button></form></section>
}
