const db=require('../../../db/knex'),repository=require('./staff-activity.repository'),notification=require('../../../services/NotificationService');const{filtersSchema,recordSchema,statusSchema}=require('./staff-activity.schema');
function error(status,message){const e=new Error(message);e.status=status;return e}function tenant(user){const id=Number(user?.shop_id);if(!Number.isInteger(id)||id<=0)throw error(403,'Select a restaurant to use staff activity.');return id}function manage(user){return user?.role==='superadmin'||user?.permissions?.includes('staff_activity.manage')}
function validateRange(filters){const days=Math.floor((new Date(`${filters.to}T00:00:00Z`)-new Date(`${filters.from}T00:00:00Z`))/86400000)+1;if(days<1||days>366)throw error(400,'Activity report ranges must contain 1 to 366 days.');return filters}
async function ownScope(user){if(manage(user))return null;const own=await db('staff_profiles').where({shop_id:tenant(user),user_id:user.id}).first('id');if(!own)throw error(403,'Your login is not linked to a staff profile.');return own.id}
async function filters(user){const shop=tenant(user);const [staff,departments]=await Promise.all([db('staff_profiles').where({shop_id:shop}).whereNot('employment_status','terminated').select('id','employee_id','full_name','department_id').orderBy('full_name').limit(500),db('staff_departments').where({shop_id:shop,is_active:true}).select('id','name').orderBy('name')]);if(manage(user))return{staff,departments};const own=await ownScope(user);return{staff:staff.filter(p=>Number(p.id)===Number(own)),departments}}
async function report(user,raw){const parsed=validateRange(filtersSchema.parse(raw)),own=await ownScope(user);return{from:parsed.from,to:parsed.to,notice:'Operational metrics are descriptive evidence only. No automatic HR performance score is calculated.',rows:await repository.report(tenant(user),parsed,own)}}
async function records(user,raw){const parsed=validateRange(filtersSchema.parse(raw)),own=await ownScope(user);return repository.records(tenant(user),parsed,own,manage(user))}
async function create(user,payload){const shop=tenant(user),data=recordSchema.parse(payload);if(data.record_type!=='task'&&data.due_date)throw error(400,'Only tasks can have a due date.');if(!await db('staff_profiles').where({id:data.staff_profile_id,shop_id:shop}).first())throw error(404,'Staff profile not found.');const row=await db.transaction(async trx=>{const[created]=await trx('staff_activity_records').insert({...data,shop_id:shop,created_by:user.id,severity:data.severity||null}).returning('*');await trx('staff_activity_record_history').insert({shop_id:shop,record_id:created.id,from_status:null,to_status:'open',actor_user_id:user.id,note:`${data.record_type.replace('_',' ')} created.`});return created});const target=await db('staff_profiles').where({id:data.staff_profile_id,shop_id:shop}).first('user_id');if(target?.user_id&&['task','recognition'].includes(data.record_type))await notification.create({shop_id:shop,target_user_id:target.user_id,type:'assignment',priority:data.severity==='high'?'high':'normal',title:data.title,message:data.details,action_label:'Open staff activity',action_url:'/app/staff',status:'active'},user).catch(()=>{});return row}
async function changeStatus(user,rawId,payload){const shop=tenant(user),id=Number(rawId),data=statusSchema.parse(payload);return db.transaction(async trx=>{const row=await trx('staff_activity_records').where({id,shop_id:shop}).forUpdate().first();if(!row)throw error(404,'Staff activity record not found.');if(row.status===data.status)return row;if(row.status==='archived')throw error(409,'Archived records cannot be changed.');const[updated]=await trx('staff_activity_records').where({id}).update({status:data.status,completed_at:data.status==='completed'?trx.fn.now():row.completed_at,updated_at:trx.fn.now()}).returning('*');await trx('staff_activity_record_history').insert({shop_id:shop,record_id:id,from_status:row.status,to_status:data.status,actor_user_id:user.id,note:data.note});return updated})}
function csvCell(value){const raw=String(value??'');const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return`"${safe.replace(/"/g,'""')}"`}
async function exportCsv(user,raw){const data=await report(user,raw);const headers=['Employee ID','Name','Department','Orders handled','Payments received','Payment amount','Register sessions','Attendance reliable days','Scheduled days','Missing clock days','Late minutes','Open tasks','Recognition records','Disciplinary records'];const lines=[headers.map(csvCell).join(',')];for(const row of data.rows)lines.push([row.employee_id,row.full_name,row.department_name||row.department,row.orders_handled,row.payments_received,row.payment_amount,row.register_sessions,row.attendance_reliable_days,row.attendance_scheduled_days,row.missing_clock_days,row.late_minutes,row.open_tasks,row.recognition_records,row.disciplinary_records].map(csvCell).join(','));return{fileName:`staff-activity-${data.from}-${data.to}.csv`,content:`\uFEFF${lines.join('\r\n')}`}}
module.exports={filters,report,records,create,changeStatus,exportCsv,csvCell};
